server:
  port: 8741
  servlet:
    context-path: /token-manager
spring:
  profiles:
    active:
      - prod
  cache:
    type: redis
  jackson:
    date-format: yyyy-MM-dd hh:mm:ss
    time-zone: GMT+8
# mybatis-plus配置
mybatis-plus:
  # MyBatis Mapper所对应的XML文件位置
  mapper-locations: classpath*:/mapper/*Mapper.xml
  configuration-properties:
    STATE_NO: 0
    STATE_YES: 1
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      # 主键类型 0:数据库ID自增 1.未定义 2.用户输入 3 id_worker 4.uuid 5.id_worker字符串表示
      id-type: ASSIGN_ID
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_NULL
      # 默认数据库表下划线命名
      table-underline: true

knife4j:
  enable: true
  openapi:
    title: Archive Editor 文档
    description: 这个Archive Editor的文档
    email: yangxinhua152@gmail.com
    url: http://192.210.197.111:8899/
    version: v4.0
    license: Apache 2.0