# 建库 - token管理器
CREATE DATABASE tm_prod;
use tm_prod;
# 游戏信息表
DROP TABLE IF EXISTS TM_GAME;
CREATE TABLE `TM_GAME` (
   ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
   NAME VARCHAR(31) NOT NULL DEFAULT '' COMMENT 'Game名称',
   DESCRIPTION VARCHAR(127) NOT NULL DEFAULT '' COMMENT 'Game描述',
   URL VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Game Token对应Url',
   ERROR_TOKEN VARCHAR(1023) NOT NULL DEFAULT '' COMMENT 'Game 对应错误TOken',
   GMT_CREATE DATETIME COMMENT '创建时间',
   GMT_MODIFIED DATETIME COMMENT '修改时间',
   DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT 'Game信息表';

# 游戏用户表
DROP TABLE IF EXISTS TM_GAME_USER;
CREATE TABLE `TM_GAME_USER` (
    ID BIGINT NOT NULL PRIMARY KEY COMMENT '主键ID',
    GAME_ID BIGINT NOT NULL COMMENT '游戏ID',
    WECHAT_NAME VARCHAR(31) NOT NULL DEFAULT '' COMMENT '微信名称',
    USER_NAME VARCHAR(31) NOT NULL DEFAULT '' COMMENT '用户游戏名称',
    TOKEN varchar(1024)  NOT NULL DEFAULT '' COMMENT '游戏用户token',
    `STATUS` TINYINT NOT NULL DEFAULT 0 COMMENT '是否启用 0 - 禁用 1 - 启用',
    GMT_CREATE DATETIME COMMENT '创建时间',
    GMT_MODIFIED DATETIME COMMENT '修改时间',
    DELETED TINYINT NOT NULL DEFAULT 0 COMMENT '逻辑删除'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '游戏用户表';
